# Generated by Django 5.0.6 on 2026-07-01 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="exercisecategory",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="musclegroup",
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                ("estimated_duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workout_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("sets", models.PositiveSmallIntegerField(default=3)),
                ("reps", models.PositiveSmallIntegerField(default=10)),
                ("rest_seconds", models.PositiveSmallIntegerField(default=60)),
                ("tempo", models.CharField(blank=True, max_length=20)),
                ("rpe", models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_exercises",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workouts.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddIndex(
            model_name="workouttemplate",
            index=models.Index(fields=["name"], name="workouts_wo_name_d4b0d7_idx"),
        ),
        migrations.AddIndex(
            model_name="workouttemplate",
            index=models.Index(fields=["difficulty"], name="workouts_wo_difficu_4f1546_idx"),
        ),
        migrations.AddIndex(
            model_name="workouttemplate",
            index=models.Index(fields=["is_active"], name="workouts_wo_is_acti_2afc5c_idx"),
        ),
        migrations.AddConstraint(
            model_name="workouttemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_workout_template_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutexercise",
            index=models.Index(fields=["workout_template"], name="workouts_wo_workout_eb79b6_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutexercise",
            index=models.Index(fields=["exercise"], name="workouts_wo_exercis_661c99_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutexercise",
            index=models.Index(fields=["order"], name="workouts_wo_order_bff5f2_idx"),
        ),
        migrations.AddConstraint(
            model_name="workoutexercise",
            constraint=models.UniqueConstraint(
                fields=("workout_template", "order"), name="uq_workout_exercise_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutexercise",
            constraint=models.UniqueConstraint(
                fields=("workout_template", "exercise"), name="uq_workout_exercise_unique"
            ),
        ),
    ]
